config/routes.rb
require 'robots_generator'

Cake::Application.routes.draw do
  use_doorkeeper

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {omniauth_callbacks: :omniauth_callbacks, registrations: :registrations, sessions: :sessions, confirmations: :confirmations}

  root to: "home#index"

  authenticated :user do
    mount Resque::Server, at: "/resque"
  end

  namespace :home, path:'/' do
    get :get_started
    get :load_tab
  end

  #Static pages
  get "/about/*id" => 'about#show', as: :about_page, format: false
  get "/help/*id" => 'help#show', as: :help_page, format: false

  resources :direct_donations, only: :create

  scope :search, controller: :searches do
    get :search_campaigns, path:'campaigns'
    get :search_sponsors, path:'sponsors'
    get :search_fundraisers, path:'fundraisers'
    get :search_coupons, path:'coupons'
  end

  resources :campaigns do
    member do
      scope :edit do
        get :tell_your_story
        get :sponsors
        get :launch_wizard, path: :launch
        get :share
      end
      get :badge, to: redirect {|params| "#{Cake::IFRAME_HOST}/badges/campaign/#{params[:id]}"}
      patch :launch
      patch :save_for_launch
      patch :toggle_visibility

      scope :pictures, controller: :cropping do
        post :crop
      end
    end
  end

  get '/hero_campaigns/:id', to: 'campaigns#hero', as:'hero_campaign'

  resources :pledges do
    collection do
      get :select_campaign
    end

    member do
      scope :edit do
        get :tell_your_story
        get :add_coupon
        get :news
        get :share
      end

      scope :pictures, controller: :cropping do
        post :crop
      end

      get :increase
      patch :set_increase
      patch :increase_request

      get :badge, to: redirect {|params| "#{Cake::IFRAME_HOST}/badges/pledge/#{params[:id]}"}
      patch :launch

      patch :accept
      patch :reject
      get :add_reject_message

      get :click
    end
  end

  resources :quick_pledges, except: :show do
    member do
      get :click
    end
  end

  resources :fundraisers, except: [:index, :destroy] do
    member do
      #get :bank_account
      #patch :set_bank_account
      scope :pictures, controller: :cropping do
        post :crop
      end
      get :request_partnership
      post :send_partnership
      get :click
    end  
  end

  resources :sponsors, except: [:index, :destroy] do
    member do
      get :credit_card
      patch :set_credit_card
      scope :pictures, controller: :cropping do
        post :crop
      end
    end 
  end

  resources :fr_sponsors, except: [:index, :show]
  
  resources :pledge_requests do
    member do
      patch :accept
      patch :reject
    end
  end

  scope :payments, controller: :payments do
    post :invoice_payment
    post :quick_invoice_payment
  end
  
  #FR Dashboard
  namespace :fundraiser, controller: :dashboard do
    get :home
    get :billing
    get :pledges
    get :campaigns
    get :history
  end

  #Sponsor Dashboard
  namespace :sponsor, controller: :dashboard do
    get :home
    get :billing
    get :pledge_requests
    get :active_pledges
    get :history
  end

  resources :coupons do
    collection do
      get :load_all
    end
    
    member do
      get :download
      scope :pictures, controller: :cropping do
        post :crop
      end

      get :click
    end
  end

  resources :pledge_news do
    collection do
      get :load_all
    end
    member do
      scope :pictures, controller: :cropping do
        post :crop
      end

      get :click
    end
  end

  namespace :locations do
    get :subregion_options
  end

  resources :impressions do
    patch :rendered
  end

  scope :browser, controller: :browsers do
    patch :fingerprint
  end

  scope :password, controller: :password, name_prefix: :password do
    get :confirm
    post :verify
  end

  #Settings
  scope :settings do
    get :public_profile, controller: :settings

    get :account, to: redirect('users/edit')
    resource :fundraiser_email_settings, only: [:edit, :update]
    resource :sponsor_email_settings, only: [:edit, :update]
  end

  resources :users, only: :index do
    collection do
      patch :roles
    end
  end

  namespace :mailers do
    post :contact
  end

  mount API::Base => '/api'

  resources :subscriptors, only: :create

  # Adds routes for evercookie under namespace (path)
  scope "#{Evercookie.get_namespace}" do
    # route for js file to set cookie
    get 'set' => "evercookie/evercookie#set", as: :evercookie_set
    # route for js file to get cookie
    get 'get' => "evercookie/evercookie#get", as: :evercookie_get
    # route for save action to save cookie value to session
    get 'save' => "evercookie/evercookie#save", as: :evercookie_save

    # route to png image to be tracked by js script
    get 'ec_png' => "evercookie/evercookie#ec_png", as: :evercookie_png
    # route to etag action to be tracked by js script
    get 'ec_etag' => "evercookie/evercookie#ec_etag", as: :evercookie_etag
    # route to cache action to be tracked by js script
    get 'ec_cache' => "evercookie/evercookie#ec_cache", as: :evercookie_cache
    # route to basic auth to be tracked by js script
    get 'ec_auth' => "evercookie/evercookie#ec_auth", as: :evercookie_auth
  end

  mount StripeEvent::Engine, at: "/stripe-webhooks"

  get "/robots.txt" => RobotsGenerator
end

app/views/campaigns/show/tables/_active_row.html.slim
- cache [:table, :active, campaign] do
  tr.campaign 
    td data-title=(Campaign.model_name.human)
      = auto_link campaign
    td data-title=(Campaign.human_attribute_name :end_date)
      = campaign.end_date
    td data-title=(Campaign.human_attribute_name :total)
      = campaign.raised
    td data-title=(t('semantic.number_of', model: 'Pledges'))
      = campaign.pledges_count
      - if campaign.pledges_count > 0
        = link_to " View", "#campaign-#{campaign.id}", data: {toggle: :modal}
    td data-title=(t('semantic.number_of', model: 'Cakesters'))
      = campaign.cakesters_list.count
      - if campaign.cakesters_list.count > 0
        = link_to " View", "#cakesters-campaign-#{campaign.id}", data: {toggle: :modal}
    td data-title=(t('semantic.average', model: 'Pledge'))
      = campaign.average_pledge
    td data-title=(t('semantic.average', model: 'Don/Click'))
      = campaign.average_donation_per_click
    td data-title=(Campaign.human_attribute_name :unique_clicks)
      = campaign.unique_clicks
    td data-title=(t('semantic.average', model: 'Clicks/Pledge'))
      = campaign.average_clicks_per_pledge
    - unless campaign.past?
      td data-title=(Campaign.human_attribute_name :status)
        = status_buttons(campaign)
    td data-title=(Campaign.human_attribute_name :visibility)
      = visibility_buttons(campaign)
    td.truncate
      = render partial:'campaigns/show/actions', locals:{campaign: campaign}
      = render partial:'campaigns/show/pledges/modal', locals:{campaign: campaign}
      = render partial:'cakesters/show/table_modal', locals:{campaign: campaign}
  tr.empty-tr

app/views/campaigns/show/tables/_active_table.html.slim
- if campaigns.any?
  #no-more-tables
    table#campaigns.table.table-hover.table-bordered.table-striped.data-table
      thead.cf
        tr
          th = Campaign.model_name.human
          th = Campaign.human_attribute_name :end_date
          th = Campaign.human_attribute_name :donations_earned
          th = t('semantic.number_of', model: 'Pledges')
          th = t('semantic.number_of', model: 'Cakesters')
          th = t('semantic.average', model: 'Pledge')
          th = t('semantic.average', model: 'Don/Click')
          th = Campaign.human_attribute_name :unique_clicks
          th = t('semantic.average', model: 'Clicks / Pledge')
          th = Campaign.human_attribute_name :status
          th = Campaign.human_attribute_name :visibility
          th
      tbody
        = render partial:'campaigns/show/tables/active_row', collection: CampaignDecorator.decorate_collection(campaigns), as: :campaign
- else
  = render partial:'layouts/no_results', locals:{object: t('titles.empty_results.campaigns')}

app/views/campaigns/show/tables/_modal.html.slim
.campaign_modal.modal.fade id="campaign_modal_#{campaign.id}"
  .modal-dialog
    .modal-content
      .modal-body
       
        - if campaign.pending?
          button.close aria-hidden="true" data-dismiss="modal" type="button" &times;
          .row.text-center.clear
            h2 Find Sponsors
            p.text-muted It's time to Find Sponsors for your Campaign. Ask Sponsors you may know to make a pay per click Pledge supporting your Campaign by following this link below!
            .toggle-container.text-left
              div
                label Campaign Url: 
                input#campaign_url.form-control disabled='' type="text" value=campaign_url(campaign.id)
              div.pull-right
                br
                button.clipboard.btn.btn-primary data-clipboard-target="campaign_url" Copy
          .row.section-wrapper.text-center
            h2 Search for Sponsors
            p.text-muted Request Pledges from Active Sponsors already on Cake
            br
            = link_to "Search for sponsors", search_sponsors_path, class:'btn btn-primary'
        - else
          button.close aria-hidden="true" data-dismiss="modal" type="button" &times;
          .row.text-center.clear
            h2 Share on Social Media
            p.text-muted This will help your Campaign reach the most people
            .share-buttons
              .addthis_sharing_toolbox#social data-url='#{campaign_url(campaign.id)}' data-title='Click and help support us! It is 100% free!'

          .row.section-wrapper.text-center
            h2 Email Your Campaign
            p.text-muted Email your Campaign directly to your friends and supporters
            .toggle-container.text-left
              div
                label Campaign Url: 
                input#campaign_url.form-control disabled='' type="text" value=campaign_url(campaign.id)
              div.pull-right
                br
                button.clipboard.btn.btn-primary data-clipboard-target="campaign_url" Copy
          .row.section-wrapper.text-center
            h2 Download Your Campaign Image
            p.text-muted You can use a PNG of your Campaign for emails and mailings
            .toggle-container.text-left
              .screenshot
                = screenshot_tag_for campaign
              div.pull-right
                br
                = link_to "Download", campaign.screenshot_url, class:'btn btn-primary', download: 'campaign.png'
          .row.section-wrapper.text-center       
            h2 Embed Badge on Your Website
            p.text-muted Copy the source code below and past it on your website
            .toggle-container.text-left
              div
                textarea#embedded_link.form-control disabled='' rows="5" 
                  iframe width='800px' height='540px' src=badge_url(campaign)
                    p 
                      | See this campaign here: 
                      = link_to campaign.mission, campaign_url(campaign.id), target: :_blank
              div.pull-right
                br
                button.clipboard.btn.btn-primary data-clipboard-target="embedded_link" Copy
  