config/routes.rb
require 'robots_generator'

Cake::Application.routes.draw do
  use_doorkeeper

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {omniauth_callbacks: :omniauth_callbacks, registrations: :registrations, sessions: :sessions, confirmations: :confirmations}

  root to: "home#index"

  authenticated :user do
    mount Resque::Server, at: "/resque"
  end

  namespace :home, path:'/' do
    get :get_started
    get :load_tab
  end

  #Static pages
  get "/about/*id" => 'about#show', as: :about_page, format: false
  get "/help/*id" => 'help#show', as: :help_page, format: false

  resources :direct_donations, only: :create

  scope :search, controller: :searches do
    get :search_campaigns, path:'campaigns'
    get :search_sponsors, path:'sponsors'
    get :search_fundraisers, path:'fundraisers'
    get :search_coupons, path:'coupons'
  end

  resources :campaigns do
    member do
      scope :edit do
        get :tell_your_story
        get :sponsors
        get :launch_wizard, path: :launch
        get :share
      end
      get :badge, to: redirect {|params| "#{Cake::IFRAME_HOST}/badges/campaign/#{params[:id]}"}
      patch :launch
      patch :save_for_launch
      patch :toggle_visibility

      scope :pictures, controller: :cropping do
        post :crop
      end
    end
  end

  get '/hero_campaigns/:id', to: 'campaigns#hero', as:'hero_campaign'

  resources :pledges do
    collection do
      get :select_campaign
    end

    member do
      scope :edit do
        get :tell_your_story
        get :add_coupon
        get :news
        get :share
      end

      scope :pictures, controller: :cropping do
        post :crop
      end

      get :increase
      patch :set_increase
      patch :increase_request

      get :badge, to: redirect {|params| "#{Cake::IFRAME_HOST}/badges/pledge/#{params[:id]}"}
      patch :launch

      patch :accept
      patch :reject
      get :add_reject_message

      get :click
    end
  end

  resources :quick_pledges, except: :show do
    member do
      get :click
    end
  end

  resources :fundraisers, except: [:index, :destroy] do
    member do
      #get :bank_account
      #patch :set_bank_account
      scope :pictures, controller: :cropping do
        post :crop
      end
      get :request_partnership
      post :send_partnership
      get :click
    end  
  end

  resources :sponsors, except: [:index, :destroy] do
    member do
      get :credit_card
      patch :set_credit_card
      scope :pictures, controller: :cropping do
        post :crop
      end
    end 
  end

  resources :fr_sponsors, except: [:index, :show]
  
  resources :pledge_requests do
    member do
      patch :accept
      patch :reject
    end
  end

  scope :payments, controller: :payments do
    post :invoice_payment
    post :quick_invoice_payment
  end
  
  #FR Dashboard
  namespace :fundraiser, controller: :dashboard do
    get :home
    get :billing
    get :pledges
    get :campaigns
    get :history
  end

  #Sponsor Dashboard
  namespace :sponsor, controller: :dashboard do
    get :home
    get :billing
    get :pledge_requests
    get :active_pledges
    get :history
  end

  resources :coupons do
    collection do
      get :load_all
    end
    
    member do
      get :download
      scope :pictures, controller: :cropping do
        post :crop
      end

      get :click
    end
  end

  resources :pledge_news do
    collection do
      get :load_all
    end
    member do
      scope :pictures, controller: :cropping do
        post :crop
      end

      get :click
    end
  end

  namespace :locations do
    get :subregion_options
  end

  resources :impressions do
    patch :rendered
  end

  scope :browser, controller: :browsers do
    patch :fingerprint
  end

  scope :password, controller: :password, name_prefix: :password do
    get :confirm
    post :verify
  end

  #Settings
  scope :settings do
    get :public_profile, controller: :settings

    get :account, to: redirect('users/edit')
    resource :fundraiser_email_settings, only: [:edit, :update]
    resource :sponsor_email_settings, only: [:edit, :update]
  end

  resources :users, only: :index do
    collection do
      patch :roles
    end
  end

  namespace :mailers do
    post :contact
  end

  mount API::Base => '/api'

  resources :subscriptors, only: :create

  # Adds routes for evercookie under namespace (path)
  scope "#{Evercookie.get_namespace}" do
    # route for js file to set cookie
    get 'set' => "evercookie/evercookie#set", as: :evercookie_set
    # route for js file to get cookie
    get 'get' => "evercookie/evercookie#get", as: :evercookie_get
    # route for save action to save cookie value to session
    get 'save' => "evercookie/evercookie#save", as: :evercookie_save

    # route to png image to be tracked by js script
    get 'ec_png' => "evercookie/evercookie#ec_png", as: :evercookie_png
    # route to etag action to be tracked by js script
    get 'ec_etag' => "evercookie/evercookie#ec_etag", as: :evercookie_etag
    # route to cache action to be tracked by js script
    get 'ec_cache' => "evercookie/evercookie#ec_cache", as: :evercookie_cache
    # route to basic auth to be tracked by js script
    get 'ec_auth' => "evercookie/evercookie#ec_auth", as: :evercookie_auth
  end

  mount StripeEvent::Engine, at: "/stripe-webhooks"

  get "/robots.txt" => RobotsGenerator
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :go_to_registration, only: :index
  before_action :block_registered_user, only: :get_started

  def index
    @carousel_pics = (Sponsor.home_logos + Fundraiser.home_logos).shuffle
    @campaigns = CampaignDecorator.decorate_collection Campaign.popular
  end

  def get_started
    session.delete(:new_user)
  end

  def load_tab
    model = params[:model].camelize

    @collection = "#{model}Decorator".constantize.decorate_collection model.constantize.popular
    render partial:"home/search/#{params[:model].pluralize}"
  end

  protected

  def block_registered_user
    redirect_to root_path if current_user.nil? or current_user.registered
  end

  def go_to_registration
    unless current_user.nil? || current_user.registered
      if current_user.fundraiser_email_setting.present? and current_fundraiser.nil?
        route = new_fundraiser_path
      elsif current_user.sponsor_email_setting.present? and current_sponsor.nil?
        route = new_sponsor_path
      else
        route = home_get_started_path
      end

      redirect_to route, notice: 'Please complete your registration in CakeCauseMarketing.'
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def home_tab_button(model, text)
    link_to home_load_tab_path(model: model), data:{toggle: 'remoteTab', target: "#pop-#{underscore_to_dash(model.to_s).pluralize}"}, id:"tab-#{underscore_to_dash(model.to_s).pluralize}" do
      content_tag(:span, text)
    end
  end
end

app/views/home/_home_video.html.slim
#home_video_fr.modal.fade
  .modal-dialog.modal-lg
    .modal-content
      .modal-header 
        button.close aria-hidden="true" data-dismiss="modal" type="button" &times;
        h2.modal-title Introducing Cake Fundraising
      .modal-body
        iframe class="youtube_video" title="Introducing Cake Fundraising" width="100%" height="500px" src="//www.youtube.com/embed/_zEtobIg5W8" frameborder="0"
    /! /.modal-content
  /! /.modal-dialog
/! /.modal

#home_video_sp.modal.fade
  .modal-dialog.modal-lg
    .modal-content
      .modal-header 
        button.close aria-hidden="true" data-dismiss="modal" type="button" &times;
        h2.modal-title Introducing Cake Cause Marketing
      .modal-body
        iframe class="youtube_video" title="Introducing Cake Cause Marketing" width="100%" height="500px" src="//www.youtube.com/embed/cgd5AZoJR70" frameborder="0"
    /! /.modal-content
  /! /.modal-dialog
/! /.modal

javascript:
  $(document).ready(Cake.videos.restartOnModalHidden("#home_video_fr"));
  $(document).ready(Cake.videos.restartOnModalHidden("#home_video_sp"));

app/views/home/get_started.html.slim
= display_meta("Get Started")

= content_for :right_nav do
  = menu_item "FAQ", root_path
  = menu_item "Help", root_path

.header.text-center
  h1 Let's Get Started!
  p.text-muted Thanks for signing up. Now, let start your first steps on CakeCauseMarketing.

.row.choose-role 
  .col-md-4.divider-vert
    .fundraisers-cir
      h2 Causes,
      p create your free "pay-per-click" campaign today!
      = link_to "Start Now!", roles_users_path(role: :fundraiser), method: :patch, class:'btn btn-success start-now-btn'
  .col-md-4.divider-vert
    .sponsors-cir
      h2 Sponsors,
      p support great causes on a risk free "pay-per-click" basis
      = link_to "Start Now!", roles_users_path(role: :sponsor), method: :patch, class:'btn btn-primary start-now-btn'
  .col-md-4
    .cakesters-cir
      h2 Cakesters,
      p earn money by connecting Sponsors & Causes!
      = link_to "Start Now!", roles_users_path(role: :cakester), method: :patch, class:'btn btn-purple start-now-btn'
.row
  .col-md-12.text-center
    p.text-muted.explore
      span I am not a Fundraiser, nor a Sponsor, nor a Cakester. I want to 
      = link_to 'cancel my account.', registration_path(current_user), method: :delete, data: {confirm: 'Are you sure?'}

app/views/home/index.html.slim
= content_for :header do 
  - cache [:home, :header] do
  	.hero-home
      = render partial:'home/banner/bg_video'
      .home-banner
        section.main-banner.text-center
          h1.boldest Create Win/Win Social Media Partnerships in Minutes!
          h2.hidden-sm.hidden-xs The World's #1 Digital Sponsorship & Partnership Platform

        section.sign-up-button
          = link_to new_user_registration_path, class:'btn btn-success btn-mega' do
            span.glyphicon.glyphicon-ok
            span  Sign Up Free
        br
        section.logos_carousel.row.hidden-sm.hidden-xs
          #home_carousel.col-md-10.col-md-push-1
            = render partial:'home/banner/carousel', collection: @carousel_pics, as: :pic

    .secondary-navbar
      ul.nav.nav-pills.popular
        li.active
          a data-toggle="tab" id="tab-campaigns" href="#pop-campaigns"
            span Campaigns Seeking Sponsors
        li
          = home_tab_button(:sponsor, 'All Sponsors')
        li
          = home_tab_button(:fundraiser, 'All Causes')
        li
          a data-toggle="tab" id="tab-cakesters" href="#pop-cakesters"
            span All Cakesters
        li
          a data-toggle="tab" id="tab-comissions" href="#pop-comissions"
            span Commissions
        li
          = home_tab_button(:coupon, 'Best Discounts')
								
.container.main-home
	= render partial:'home/search/section'

= content_for :bottom_section do
  .easy-band
    .pointer-b
    h2 Online Fundraising Has Never Been Easier
    .container
      .row.center
        .circle-campaign
          .totals-centerd
            h4 = campaigns_count
            p.total-type CAMPAIGNS
        .circle-sp
          .totals-centerd
            h4 = sponsors_count
            p.total-type SPONSORS
        .circle-raised
          .totals-centerd
            h4 = global_raised
            p.total-type RAISED
      h3 Let your friends know that Cake is the best way to raise money online.
      .share-block-wrap
        .text-center
          .share-buttons
            .addthis_jumbo_share#social
  .quotes
    .container.quote-container
      .row
        h4.boldest.quote Cake Fundraising is a fabulous platform and I’m certain it will be a huge success.
    .container
      .row
        .col-xs-6
        .col-xs-6
          h4.boldest.author
            | - Robin Clause
              <br class='rwd-break' />
                (Coca-Cola)
    .container.quote-container
      .row
        h4.boldest.quote Your platform is very interesting and I think has the chance to revolutionize how non-profits and similar entities raise funds.
    .container
      .row
        .col-xs-6
        .col-xs-6
          h4.boldest.author
            | - Jason Herndon
              <br class='rwd-break' />
                (Lupus Foundation)
    br
    br

  .supporters
    .container
      / .row.text-center
      /   br
      /   h3 OUR USERS
      / .row.section-wrapper.text-center

      .row.text-center
        br
        h3 OUR SUPPORTERS
      .row.section-wrapper.text-center
        img src='/assets/partners/logo_bj.gif'/
        img src='/assets/partners/logo_techc.gif'/
        img src='/assets/partners/logo_etc.gif'/
        img src='/assets/partners/logo_tb.gif'/
        /img src='/assets/partners/logo_chitrib.gif'/
        /img src='/assets/partners/logo_cnn.gif'/
        /img src='/assets/partners/logo_forbes.gif'/
        /img src='/assets/partners/logo_huff.gif'/
        /img src='/assets/partners/logo_mashable.gif'/
        /img src='/assets/partners/logo_nyt.gif'/
        /img src='/assets/partners/logo_tc.gif'/
        img src='/assets/partners/logo_tech.gif'/