config/routes.rb
require 'robots_generator'

Cake::Application.routes.draw do
  use_doorkeeper

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {omniauth_callbacks: :omniauth_callbacks, registrations: :registrations, sessions: :sessions, confirmations: :confirmations}

  root to: "home#index"

  authenticated :user do
    mount Resque::Server, at: "/resque"
  end

  namespace :home, path:'/' do
    get :get_started
    get :load_tab
  end

  #Static pages
  get "/about/*id" => 'about#show', as: :about_page, format: false
  get "/help/*id" => 'help#show', as: :help_page, format: false

  resources :direct_donations, only: :create

  scope :search, controller: :searches do
    get :search_campaigns, path:'campaigns'
    get :search_sponsors, path:'sponsors'
    get :search_fundraisers, path:'fundraisers'
    get :search_coupons, path:'coupons'
  end

  resources :campaigns do
    member do
      scope :edit do
        get :tell_your_story
        get :sponsors
        get :launch_wizard, path: :launch
        get :share
      end
      get :badge, to: redirect {|params| "#{Cake::IFRAME_HOST}/badges/campaign/#{params[:id]}"}
      patch :launch
      patch :save_for_launch
      patch :toggle_visibility

      scope :pictures, controller: :cropping do
        post :crop
      end
    end
  end

  get '/hero_campaigns/:id', to: 'campaigns#hero', as:'hero_campaign'

  resources :pledges do
    collection do
      get :select_campaign
    end

    member do
      scope :edit do
        get :tell_your_story
        get :add_coupon
        get :news
        get :share
      end

      scope :pictures, controller: :cropping do
        post :crop
      end

      get :increase
      patch :set_increase
      patch :increase_request

      get :badge, to: redirect {|params| "#{Cake::IFRAME_HOST}/badges/pledge/#{params[:id]}"}
      patch :launch

      patch :accept
      patch :reject
      get :add_reject_message

      get :click
    end
  end

  resources :quick_pledges, except: :show do
    member do
      get :click
    end
  end

  resources :fundraisers, except: [:index, :destroy] do
    member do
      #get :bank_account
      #patch :set_bank_account
      scope :pictures, controller: :cropping do
        post :crop
      end
      get :request_partnership
      post :send_partnership
      get :click
    end  
  end

  resources :sponsors, except: [:index, :destroy] do
    member do
      get :credit_card
      patch :set_credit_card
      scope :pictures, controller: :cropping do
        post :crop
      end
    end 
  end

  resources :fr_sponsors, except: [:index, :show]
  
  resources :pledge_requests do
    member do
      patch :accept
      patch :reject
    end
  end

  scope :payments, controller: :payments do
    post :invoice_payment
    post :quick_invoice_payment
  end
  
  #FR Dashboard
  namespace :fundraiser, controller: :dashboard do
    get :home
    get :billing
    get :pledges
    get :campaigns
    get :history
  end

  #Sponsor Dashboard
  namespace :sponsor, controller: :dashboard do
    get :home
    get :billing
    get :pledge_requests
    get :active_pledges
    get :history
  end

  resources :coupons do
    collection do
      get :load_all
    end
    
    member do
      get :download
      scope :pictures, controller: :cropping do
        post :crop
      end

      get :click
    end
  end

  resources :pledge_news do
    collection do
      get :load_all
    end
    member do
      scope :pictures, controller: :cropping do
        post :crop
      end

      get :click
    end
  end

  namespace :locations do
    get :subregion_options
  end

  resources :impressions do
    patch :rendered
  end

  scope :browser, controller: :browsers do
    patch :fingerprint
  end

  scope :password, controller: :password, name_prefix: :password do
    get :confirm
    post :verify
  end

  #Settings
  scope :settings do
    get :public_profile, controller: :settings

    get :account, to: redirect('users/edit')
    resource :fundraiser_email_settings, only: [:edit, :update]
    resource :sponsor_email_settings, only: [:edit, :update]
  end

  resources :users, only: :index do
    collection do
      patch :roles
    end
  end

  namespace :mailers do
    post :contact
  end

  mount API::Base => '/api'

  resources :subscriptors, only: :create

  # Adds routes for evercookie under namespace (path)
  scope "#{Evercookie.get_namespace}" do
    # route for js file to set cookie
    get 'set' => "evercookie/evercookie#set", as: :evercookie_set
    # route for js file to get cookie
    get 'get' => "evercookie/evercookie#get", as: :evercookie_get
    # route for save action to save cookie value to session
    get 'save' => "evercookie/evercookie#save", as: :evercookie_save

    # route to png image to be tracked by js script
    get 'ec_png' => "evercookie/evercookie#ec_png", as: :evercookie_png
    # route to etag action to be tracked by js script
    get 'ec_etag' => "evercookie/evercookie#ec_etag", as: :evercookie_etag
    # route to cache action to be tracked by js script
    get 'ec_cache' => "evercookie/evercookie#ec_cache", as: :evercookie_cache
    # route to basic auth to be tracked by js script
    get 'ec_auth' => "evercookie/evercookie#ec_auth", as: :evercookie_auth
  end

  mount StripeEvent::Engine, at: "/stripe-webhooks"

  get "/robots.txt" => RobotsGenerator
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  include Statusable
  include Fees

  has_statuses :due_to_pay, :paid

  MIN_DUE = 0.5

  belongs_to :pledge, touch: true
  has_one :campaign, through: :pledge
  has_one :fundraiser, through: :campaign
  has_one :sponsor, through: :pledge, source_type: 'Sponsor'
  has_one :cakester, through: :pledge

  has_one :payment, as: :item
  has_many :charges, through: :payment

  monetize :click_donation_cents
  monetize :due_cents
  monetize :fees_cents
  monetize :cakester_commission_cents

  scope :outstanding, ->{ where.not(status: :paid) }
  scope :latest, ->{ order(created_at: :desc) }

  scope :quick, ->{ where(type: 'QpInvoice') }
  scope :normal, ->{ where(type: nil) }

  delegate :bonus_clicks_count, to: :pledge

  def payable?
    self.due_cents > 50
  end

  def has_cakester?
    self.cakester_commission_cents.present?
  end

  def self.create_from_pledge!(pledge)
    status = (pledge.total_charge < MIN_DUE) ? :paid : :due_to_pay
    
    pledge.build_invoice(
      clicks: pledge.clicks_count, 
      click_donation: pledge.amount_per_click, 
      due: pledge.total_charge,
      fees_cents: Invoice.calculate_fees(pledge.total_charge_cents),
      net_amount_cents: Invoice.fr_net_amount(pledge),
      cakester_rate: pledge.cakester_rate,
      cakester_commission_cents: Invoice.calculate_cakester_commission(pledge),
      status: status
    ).save!
  end

  protected

  def self.fr_net_amount(pledge)
    if pledge.cakester? and pledge.cakester_rate.present?
      net_amount = self.net_amount(pledge.total_charge_cents)
      amount = (net_amount*((100-pledge.cakester_rate).to_f/100)).round
    else
      amount = self.net_amount(pledge.total_charge_cents)
    end
    amount
  end

  def self.calculate_cakester_commission(pledge)
    if pledge.cakester? and pledge.cakester_rate.present?
      net_amount = self.net_amount(pledge.total_charge_cents)
      commission = (net_amount*(pledge.cakester_rate.to_f/100)).round
      net_commission = (commission*(1-Cake::CAKESTER_FEE)).round
    else
      net_commission = 0
    end
    net_commission
  end

end

app/models/quick_pledge.rb
class QuickPledge < Pledge
  has_one :invoice, class_name: 'QpInvoice', foreign_key: :pledge_id

  before_create do
    self.status = :accepted
  end

  after_create :notify_sponsor

  validates :name, :website_url, :campaign, :sponsor_id, :sponsor_type, presence: true
  validates :website_url, format: {with: DOMAIN_NAME_REGEX, message: I18n.t('errors.url')}
  validates :amount_per_click, numericality: {greater_than: 0, less_than_or_equal_to: 1000}
  validates :total_amount, numericality: {greater_than_or_equal_to: 50}
  validates :terms, acceptance: true, if: :new_record?

  validate :max_amount, :total_amount_greater_than_amount_per_click, :not_hero_campaign

  def create_invoice
    build_invoice(clicks: clicks_count, click_donation: amount_per_click, due: total_charge).save!
  end

  private

  def notify_sponsor
    PledgeNotification.qp_created(self.id).deliver
  end

  def not_hero_campaign
    if self.campaign.present?
      errors.add(:campaign, "Hero campaigns cannot have quick pledges.") if self.campaign.hero
    end
  end
end

app/controllers/quick_pledges_controller.rb
class QuickPledgesController < InheritedResources::Base
  load_and_authorize_resource
  
  def index
    @fr_sponsors = current_fundraiser.fr_sponsors.latest.decorate
  end

  def new
    @quick_pledge = QuickPledge.new(sponsor_id: params[:sponsor_id], sponsor_type: params[:sponsor_type])
  end

  def create
    create! do |success, failure|
      success.html do
        redirect_to quick_pledges_path, notice: 'Pledge created succesfully.'
      end
    end
  end

  def update
    update! do |success, failure|
      success.html do
        redirect_to quick_pledges_path, notice: 'Pledge updated succesfully.'
      end
    end
  end

  def destroy
    destroy! do |success, failure|
      success.html do
        redirect_to quick_pledges_path, notice: 'Pledge deleted.'
      end
      failure.html do
        redirect_to quick_pledges_path, alert: 'There was an error when deleting this pledge. Please try again.'
      end
    end
  end

  def click
    if current_browser.present?
      if resource.active?
        click = (resource.unique_click_browsers.include?(current_browser) || resource.fully_subscribed?) ? resource.bonus_clicks.build(browser: current_browser) : resource.clicks.build(browser: current_browser)

        if click.save
          click.pusherize
          redirect_to resource.decorate.website_url 
        else
          redirect_to resource, alert: click.errors.messages
        end
      else
        redirect_to resource.decorate.website_url
      end
    else
      redirect_to resource, alert: 'There was an error when trying to count your click. Please try again.'
    end
  end

  def permitted_params
    params.permit(
      quick_pledge: [
        :name, :amount_per_click, :total_amount, :website_url, :terms, :campaign_id,
        :sponsor_id, :sponsor_type,
        picture_attributes: [
          :id, :banner, :avatar, :avatar_caption,
          :avatar_crop_x, :avatar_crop_y, :avatar_crop_w, :avatar_crop_h,
          :banner_crop_x, :banner_crop_y, :banner_crop_w, :banner_crop_h
        ]
      ]
    )
  end
end

app/helpers/quick_pledges_helper.rb
module QuickPledgesHelper
end

app/views/quick_pledges/invoices/_checkout_form.html.slim
script src="https://checkout.stripe.com/checkout.js" 

= semantic_form_for Payment.new, url: quick_invoice_payment_path, html: {id:'quick_invoice_payment'} do |f|
  = f.inputs nil do
    = f.input :item_id, as: :hidden
    = f.input :card_token, as: :hidden

javascript:
  Cake.quick_invoice_payment = function(){
    window.Cake.quick_invoice_payment_handler = StripeCheckout.configure({
      key: '#{Rails.configuration.stripe[:publishable_key]}',
      token: function(token, args) {
        $("#quick_invoice_payment #payment_card_token").val(token.id);
        $("#quick_invoice_payment")[0].submit();
      }
    });
  }();

app/views/quick_pledges/invoices/_row.html.slim
- cache [:table, :quick_pledge, invoice] do 
  tr.invoice
    td data-title=(Invoice.model_name.human)
      = invoice.id
    td data-title=(Campaign.model_name.human)
      = auto_link invoice.campaign
    td data-title=(Pledge.model_name.human)
      = auto_link invoice.pledge
    td data-title=(Invoice.human_attribute_name :unique_clicks)
      = invoice.clicks
    td data-title=(Invoice.human_attribute_name :bonus_clicks)
      = invoice.bonus_clicks_count
    td data-title=(Invoice.human_attribute_name :amount_click)
      = invoice.click_donation
    td data-title=(Invoice.human_attribute_name :amount_due)
      = humanized_money_with_symbol invoice.total_fees
    td.truncate.min-width
      - if invoice.due_to_pay? and invoice.payable?
        = invoice_pay_button(invoice) 
      - elsif !invoice.payable?
        button.btn.btn-success.disabled FREE

  tr.empty-tr

  javascript:
    $(".pay_button.invoice_#{invoice.object.id}").off("click").click(function(e) {
      e.preventDefault();

      Cake.quick_invoice_payment_handler.open({
        image: '#{invoice.campaign.picture.avatar}',
        name: "Invoice #{invoice.id} Payment",
        description: 'From #{invoice.campaign}',
        amount: "#{invoice.total_fees_cents}"
      });

      $('#payment_item_id').val('#{invoice.object.id}');
    });    

app/views/quick_pledges/invoices/_table.html.slim
- if invoices.any?
  #no-more-tables
    table.table.table-hover.table-bordered.table-striped.data-table
      thead.cf
        tr
          th = Invoice.model_name.human
          th = Campaign.model_name.human
          th = Pledge.model_name.human
          th = Invoice.human_attribute_name :unique_clicks
          th = Invoice.human_attribute_name :bonus_clicks
          th = Invoice.human_attribute_name :amount_click
          th = Invoice.human_attribute_name :amount_due
          /th = Invoice.human_attribute_name :status
          th
      tbody
        = render partial:'quick_pledges/invoices/row', collection: invoices, as: :invoice

  = render partial:'quick_pledges/invoices/checkout_form'

- else
  = render partial:'layouts/no_results', locals:{object: t("titles.empty_results.invoices.qp")}