config/routes.rb
require 'robots_generator'

Cake::Application.routes.draw do
  use_doorkeeper

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {omniauth_callbacks: :omniauth_callbacks, registrations: :registrations, sessions: :sessions, confirmations: :confirmations}

  root to: "home#index"

  authenticated :user do
    mount Resque::Server, at: "/resque"
  end

  namespace :home, path:'/' do
    get :get_started
    get :load_tab
  end

  #Static pages
  get "/about/*id" => 'about#show', as: :about_page, format: false
  get "/help/*id" => 'help#show', as: :help_page, format: false

  resources :direct_donations, only: :create

  scope :search, controller: :searches do
    get :search_campaigns, path:'campaigns'
    get :search_sponsors, path:'sponsors'
    get :search_fundraisers, path:'fundraisers'
    get :search_coupons, path:'coupons'
  end

  resources :campaigns do
    member do
      scope :edit do
        get :tell_your_story
        get :sponsors
        get :launch_wizard, path: :launch
        get :share
      end
      get :badge, to: redirect {|params| "#{Cake::IFRAME_HOST}/badges/campaign/#{params[:id]}"}
      patch :launch
      patch :save_for_launch
      patch :toggle_visibility

      scope :pictures, controller: :cropping do
        post :crop
      end
    end
  end

  get '/hero_campaigns/:id', to: 'campaigns#hero', as:'hero_campaign'

  resources :pledges do
    collection do
      get :select_campaign
    end

    member do
      scope :edit do
        get :tell_your_story
        get :add_coupon
        get :news
        get :share
      end

      scope :pictures, controller: :cropping do
        post :crop
      end

      get :increase
      patch :set_increase
      patch :increase_request

      get :badge, to: redirect {|params| "#{Cake::IFRAME_HOST}/badges/pledge/#{params[:id]}"}
      patch :launch

      patch :accept
      patch :reject
      get :add_reject_message

      get :click
    end
  end

  resources :quick_pledges, except: :show do
    member do
      get :click
    end
  end

  resources :fundraisers, except: [:index, :destroy] do
    member do
      #get :bank_account
      #patch :set_bank_account
      scope :pictures, controller: :cropping do
        post :crop
      end
      get :request_partnership
      post :send_partnership
      get :click
    end  
  end

  resources :sponsors, except: [:index, :destroy] do
    member do
      get :credit_card
      patch :set_credit_card
      scope :pictures, controller: :cropping do
        post :crop
      end
    end 
  end

  resources :fr_sponsors, except: [:index, :show]
  
  resources :pledge_requests do
    member do
      patch :accept
      patch :reject
    end
  end

  scope :payments, controller: :payments do
    post :invoice_payment
    post :quick_invoice_payment
  end
  
  #FR Dashboard
  namespace :fundraiser, controller: :dashboard do
    get :home
    get :billing
    get :pledges
    get :campaigns
    get :history
  end

  #Sponsor Dashboard
  namespace :sponsor, controller: :dashboard do
    get :home
    get :billing
    get :pledge_requests
    get :active_pledges
    get :history
  end

  resources :coupons do
    collection do
      get :load_all
    end
    
    member do
      get :download
      scope :pictures, controller: :cropping do
        post :crop
      end

      get :click
    end
  end

  resources :pledge_news do
    collection do
      get :load_all
    end
    member do
      scope :pictures, controller: :cropping do
        post :crop
      end

      get :click
    end
  end

  namespace :locations do
    get :subregion_options
  end

  resources :impressions do
    patch :rendered
  end

  scope :browser, controller: :browsers do
    patch :fingerprint
  end

  scope :password, controller: :password, name_prefix: :password do
    get :confirm
    post :verify
  end

  #Settings
  scope :settings do
    get :public_profile, controller: :settings

    get :account, to: redirect('users/edit')
    resource :fundraiser_email_settings, only: [:edit, :update]
    resource :sponsor_email_settings, only: [:edit, :update]
  end

  resources :users, only: :index do
    collection do
      patch :roles
    end
  end

  namespace :mailers do
    post :contact
  end

  mount API::Base => '/api'

  resources :subscriptors, only: :create

  # Adds routes for evercookie under namespace (path)
  scope "#{Evercookie.get_namespace}" do
    # route for js file to set cookie
    get 'set' => "evercookie/evercookie#set", as: :evercookie_set
    # route for js file to get cookie
    get 'get' => "evercookie/evercookie#get", as: :evercookie_get
    # route for save action to save cookie value to session
    get 'save' => "evercookie/evercookie#save", as: :evercookie_save

    # route to png image to be tracked by js script
    get 'ec_png' => "evercookie/evercookie#ec_png", as: :evercookie_png
    # route to etag action to be tracked by js script
    get 'ec_etag' => "evercookie/evercookie#ec_etag", as: :evercookie_etag
    # route to cache action to be tracked by js script
    get 'ec_cache' => "evercookie/evercookie#ec_cache", as: :evercookie_cache
    # route to basic auth to be tracked by js script
    get 'ec_auth' => "evercookie/evercookie#ec_auth", as: :evercookie_auth
  end

  mount StripeEvent::Engine, at: "/stripe-webhooks"

  get "/robots.txt" => RobotsGenerator
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  include HighVoltage::StaticPage
 
  CONTENT_PATH = 'about/'

  def page_finder
    page_finder_factory.new(params[:id], CONTENT_PATH)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/views/about/cake.html.slim
= display_meta("About Cake")

.row
	h1.dash-head About Us
.row
	.col-md-8
		h3 Cake’s mission is to help as many people as possible.
		p 90% of US consumers prefer to do business with and are more loyal to companies that give back to the community. 50% of consumers are even willing to pay more if a company is associated with a good cause. Now with Cake, companies and good causes can create powerful win/win social media partnerships in minutes. Now companies can powerfully promote their goods and services to highly targeted demographics through engaging partnerships with good causes!
		p Please get to know and do business with the companies that support the causes you love. We vote for the world we want with each dollar we spend. So pay it forward with every purchase!
		h3 Is Cake a nonprofit?
		p 
			' Cake is a for-profit company that works to empower non-profits and good causes, and anyone else who wants to raise money online for something that they believe in. Cake will soon register as a certified
			a href="http://benefitcorp.net" Public Benefit Corporation
			' , which means that Cake will be required to operate in a manner that harms none, benefits all and protects the environment too. 
		p
			' Please see
			a href="http://benefitcorp.net" http://benefitcorp.net
			'  for additional details about Public Benefit Corporations.

		br
		h4 “You must be the change you wish to see in the world.” Mahatma Gandhi.
		br
	.col-md-1
	.col-md-3
		h3 Start or sponsor a Cake campaign today and share it with your family and friends. Make a difference with every click!
		= link_to "Sign Up Today!", new_user_registration_path, class:'btn btn-success btn-md'

.row
  .col-md-6
    h1 How Cake Works for Non-Profits
    iframe title="How Cake Works for Non-Profits" width="100%" height="400px" src="//www.youtube.com/embed/XYldI7HTh50" frameborder="0" allowfullscreen="1"	
    hr
    h1 Boy Scouts & Great Outdoor Provision Co. Campaign
    iframe title="Boy Scouts & Great Outdoor Provision Co. Campaign" width="100%" height="400px" src="//www.youtube.com/embed/WcEylaGBqkk" frameborder="0" allowfullscreen="1"
    hr
    h1 Contact Us!
    h2.text-muted We'd love to hear from you. Please contact us #{link_to 'here', about_page_path('contact')}
  .col-md-6
    h1 How Cake Works for Business
    div = image_tag('press/how-it-works.jpg', class:'img-responsive')

app/views/about/contact.html.slim
= display_meta("Contact Us")

h1.dash-head Contact Us

h4 Please use this form to leave us your details
p A Cake representative will contact you shortly.

hr 

= render partial:'contact_mailer/form'

br

app/views/about/fundraising.html.slim
h1 Cake Fundraising

h1 COMING SOON

app/views/about/how_cake_works.html.slim
= display_meta("How Cake works?")

.row.col-md-12.about-page
  h1.dash-head How Cake works?
  p Cake is a digital sponsorship and partnership platform.
  p It allows and promotes win/win partnerships between Non-Profits and Bussines Sponsors.

  / hr
  / .row
  /   .col-md-3
  /     h2 Fundraiser
  /     p A Fundraiser creates a Campaign Page for a good deed.
  /   .col-md-3
  /     h2 Campaign
  /     p The Campaign page summarizes the mission, sets a goal amount, an end date and includes all Pleges created by supporter Sponsors. 
  /   .col-md-3
  /     h2 Pledge
  /     p The Sponsor creates a Pledge to support the Campaign. It includes a pledged amount per click up to a ceiling amount. Optionally it might include coupons and PR statements.
  /   .col-md-3
  /     h2 Sponsor
  /     p The business Sponsor seeks a compelling Campaign and creates a Pledge.
  /   .col-md-12.text-center
  /     h2 Supporter
  /     p Fundraiser's supporters visit Campaign page and click on the Pledge/s to earn the pledged amount for the Fundraiser
  / hr
.row
  .col-md-6
    h3 Single-Sponsor Hero Campaign
    br
    iframe id="hero_campaign_video" title="Single Sponsor Hero Campaign" width="100%" height="400px" src="//www.youtube.com/embed/SUKPl708lhU?theme=light" frameborder="0" allowfullscreen
  .col-md-6
    h3 Multi-Sponsor Campaign
    br
    iframe id="hero_campaign_video" title="Single Sponsor Hero Campaign" width="100%" height="400px" src="//www.youtube.com/embed/12BS_9tXzwc?theme=light" frameborder="0" allowfullscreen

app/views/about/press.html.slim
= display_meta("Press")

.container
  .row
    .col-md-3
      h1.dash-head Press
    .col-md-8
      br
  .row
    .col-md-3
      br
      img src='/assets/press/tec-press.png'/
    .col-md-9
      h3.boldest You click, sponsors pay: Cake Fundraising’s new twist on giving
      p Technical.ly, October 25, 2014
      p = '"The site works like a crowdfunding platform similar to Kickstarter or GoFundMe, but with a bent toward directing visitors to sponsors, who pledge a certain amount per click. Nonprofits and businesses can filter and search Cake’s marketplace to find each other, and there is no upfront cost for either side."'
      = link_to "Read the full article", "http://technical.ly/baltimore/2014/10/15/cake-fundraising-new-twist-justin-kersey/"
  br
  hr
  .row
    .col-md-3
      br
      img src='/assets/press/bbj-press.png'/
    .col-md-9
      h3.boldest This startup thinks fundraising should be cake for nonprofits
      p Baltimore Business Journal, October 1, 2014
      p = '"Cake’s platform would make it easier for small nonprofits and businesses to participate by standardizing pledge agreements and handling payments. Here’s how it works: A nonprofit and a business connect through Cake for a social media fundraising campaign. With help from Cake, the nonprofit sets up a social media campaign that is designed to drive traffic to its business partner’s website."'
      = link_to "Read the full article", "http://www.bizjournals.com/baltimore/news/2014/10/01/this-startup-thinks-fundraising-should-be-cake-for.html"
  br
  br

app/views/about/privacy.html.slim
= display_meta("Privacy Policy")

h1.dash-head Privacy Policy
p Cake Inc. (referred to throughout as “Cake,” “us,” “we,” “our,” etc.), is the owner and operator of the www.CakeCauseMarketing.com website, a fundraising platform. This Privacy Policy applies to the www.CakeCauseMarketing.com website, any subdomains thereof, any API integrations or widgets we offer, any other websites or webpages we own or operate that include a link to this policy, and any of our mobile applications (all of which together are referred to as the “Sites”). Please keep in mind that this Privacy Policy does not apply to other websites, which may be accessible from the Sites. External websites may have data collection, storage, and use practices and policies that differ materially from those contained here.
p We may update this Privacy Policy from time to time. If we do so, we will notify you by posting the date of the last change or amendment at the top of this page. You agree that this method of notice is sufficient and that you will regularly check this Privacy Policy to see if updates or changes have been made. By continuing to use the Sites, you consent to the revised Privacy Policy.

// ---------------------------------------------------------------------------------------------------------

h3 What Types of Information Do We Collect and How?

h5 PERSONAL INFORMATION.
p In order for you to make donations through the Sites, register with the Sites, or take certain other actions on the Sites , we may require you to provide us with applicable information that personally identifies you (“Personal Information”). Personal Information includes the following types of data:
ul
  li Contact Data such as name, mailing address, e-mail address, and Cake user-name, account number, and password
  li Financial Data such as your account or credit card number
  li Demographic Data such as your zip code, age, and gender
  li Company Data such as your business name, size, and business type
  li Activity Data such as your donation history, fundraising history, events attended, etc.
  li Social Media information such as friend lists, likes, photos, and other information
 
h5 How do we collect Personal Information?
p We collect Personal Information when you provide it to us, such as when you create an account, make a donation, create a campaign, enter a contest or sweepstakes, take other actions on the Sites, and at other times.  We also collect Personal Information from social media sites and services when you use your social media account to log into the Sites or use the Sites to take other actions on social media, such as sharing or liking a fundraising campaign.

h5 Traffic Data.
p As is true of most websites, we automatically collect certain information when you visit our Sites. This information includes: (i) IP addresses, (ii) domain servers, (iii) types of computers accessing the Sites, (iv) types of web browsers used to access the Sites, (v) referring/exit pages, (vi) data about usage patterns throughout the Sites (e.g. click rates on different links etc.). Information of this type (“Traffic Data”) is anonymous information that does not personally identify you but is helpful for us to improve the business performance and user experience of the Sites.

h5 How do we collect Traffic Data?
p As is true of most websites, we use cookies (a small text file placed on your computer or device to identify your computer and web browser) to collect Traffic Data related to the Sites. We use Service Providers (defined below) to place cookies on your computer or device to compile this non-personally identifiable information so we can aggregate statistical information about usage of the Sites. Most web browsers are initially set up to accept cookies.  You can reset your web browser to refuse all cookies or to indicate when a cookie is being sent, however, certain features of the Site or Services may not work if you delete or disable cookies.
p The Sites also contain web beacons, which are electronic images that are used along with cookies to compile statistics so we can analyze how the Sites are being used. Our e-mails may also contain web beacons so we can track how many people open the message or click on links within the message. This information helps us improve our communication and marketing efforts. We use a Service Provider to gather information on how you and others are using the Sites. By using this service we are able (for example) to see how many people visited a given page or clicked on a given link. This information helps us optimize the performance of the Sites.

// ---------------------------------------------------------------------------------------------------------

h3 Is my Personal Information kept confidential?
p Except as otherwise provided in this Privacy Policy or agreed by User, we will keep your Personal Information private and will not share it with other third parties unless such disclosure is necessary to: (i) comply with a court order or other legal process, (ii) to protect our rights or property, (iii) in connection with our sale, merger, consolidation, change of control, or transfer of substantial assets, or (iv) to enforce our Terms of Service. Please keep in mind that while we take reasonable precautions to safeguard your Personal Information no amount of protection can guarantee its security.

// ---------------------------------------------------------------------------------------------------------

h3 Who has access to my Personal Information?
p We share your Personal information with other business partners who assist us in performing core services related to the operation of the Sites (“Service Providers”). These Service Providers only use your Personal Information to perform these core services, which are necessary for the orderly operation of the Sites, such as hosting and maintenance, data storage and management, security, payment processing, and marketing and promotions. Each Service Provider must agree to use reasonable security procedures and practices, appropriate to the nature of the information involved, in order to protect your Personal Information from unauthorized access, use, or disclosure.
p Unless you donate anonymously, any organization you make a contribution to, or purchase from, through the Sites will have access to your Personal Information (except for your credit card number or other payment account information). If you make a donation or purchase through an individual fundraising page, then the person who created the fundraising page will also have access to your Personal Information (except for your credit card number or other payment account information). If you make a donation or purchase through an individual fundraising page associated with a fundraising team, or directly to a team fundraising page, then the person who created the team page will also have access to your Personal Information (again, except for your credit card number or other payment account information). You consent to the foregoing and agree that we are not responsible for how these organizations or persons handle your Personal Information. You should contact them directly for their privacy policies and data usage practices. From time to time, businesses or other entities will run campaigns to benefit charities through the Sites. In such a situation, your Personal Information (except for credit card number or other payment account information) may be accessible to the business or other entity running the campaign. If that is the case, we will provide additional notice to you during checkout to let you know if the business or other entity will have access to your data.
p Please remember that after we disclose Personal Information to third parties, we can no longer control the use of such Personal Information. Accordingly, Cake will not be liable for the acts or omissions of any third party.

// ---------------------------------------------------------------------------------------------------------

h3 How does Cake use my Personal Information?
p We use your information in a variety of ways to help us run the Sites, provide services to you, and communicate with you. Here are some examples of the ways we use your information:

ul
  li To facilitate the processing of a transaction between you and a third party
  li To send you receipts
  li To send you updates about the Sites
  li To send you updates about activity on the Sites related to you
  li To administer your account
  li To respond to customer service inquiries
  li To send marketing materials
  li To improve our Sites and marketing efforts
  
// ---------------------------------------------------------------------------------------------------------

h3 Who has access to my payment information?
p Cake contracts with Service Providers to process all donations and payments made through the Sites. Only the third party processors have access to your credit card number or other payment account information. We do not have access to your credit card number or other payment account information, nor do the organizations to whom you donate, or the people who create fundraising pages. Data handled by the third party processors is subject to theirs terms and privacy policies. Please contact us at the contact information below for any additional questions about your payment information and how payments are processed.

// ---------------------------------------------------------------------------------------------------------

h3 What other information is public?
p Information you post on the Sites, event pages, campaign pages, personal fundraising or pledge pages, your profile (unless hidden), a charity or sponsor profile, blog posts, or other public pages on the Sites can be accessed by other people. You should exercise caution when deciding to share information on public pages. We cannot control who accesses shared information or how other parties will use that information.

// ---------------------------------------------------------------------------------------------------------

h3 What choices do I have?
p It’s up to you whether or not you want to provide us with Personal Information. You can still visit the Sites without providing us with Personal information, but you will be unable to take certain actions without doing so.

// ---------------------------------------------------------------------------------------------------------

h3 How can I update or correct my Personal Information?
p If you have registered (and therefore have a profile) you can update your information by clicking on “Account Settings” which is accessible at the top of your screen once you’ve logged in.

// ---------------------------------------------------------------------------------------------------------

h3 Security
p No data transmission over the Internet or other network can be guaranteed to be 100% secure. As a result, while we strive to protect information transmitted on or through the Sites, we cannot and do not guarantee the security of any information you transmit on or through the Sites, and you do so at your own risk.

// ---------------------------------------------------------------------------------------------------------

h3 Links To Other Websites
p Our Sites may contain links to or frame other websites or allow others to send you such links. A link to or framing of a third party’s website does not mean that we endorse it or that we are affiliated with it. We do not exercise control over third-party websites. You access such third-party websites or content at your own risk.  You should always read the privacy policy of a third-party website before providing any information to the website.

// ---------------------------------------------------------------------------------------------------------

h3 Children’s Privacy
p We understand the importance of protecting privacy especially where children are involved, and we are committed to doing so. Our Sites are for a general audience and are not targeted towards children. In order to protect the privacy of children, our Sites do not knowingly collect personal information from children under the age of 13 without prior parental consent. If your child has used the Sites and submitted Personal Information to us, please contact us and we will endeavor to remove that information from the Sites and our database.

// ---------------------------------------------------------------------------------------------------------

h3 Processing in the United States
p Please be aware that your Personal Information, communications, and other information may be transferred to and maintained on servers or databases located outside your state, province, or country.  If you are located outside of the United States, please be advised that we process and store all information in the United States.  The laws in the United States may not be as protective of your privacy as those in your location.  By using the Sites, you agree that the collection, use, transfer, and disclosure of your Personal Information and communications will be governed by the applicable laws in the United States.

// ---------------------------------------------------------------------------------------------------------

h3 Contact Information
p = mail_to 'justin@cakecausemarketing.com', 'justin@cakecausemarketing.com'
br

app/views/about/sponsoring.html.slim
h1 Cake Sponsoring

h1 COMING SOON

app/views/about/success_stories.html.slim
= display_meta("Success Stories")

.row
  .col-md-8
    h1.dash-head Success Stories
    iframe title="Boy Scouts & Great Outdoor Provision Co. Campaign" width="100%" height="400px" src="//www.youtube.com/embed/WcEylaGBqkk" frameborder="0" allowfullscreen="1"
    hr
    div = image_tag('press/success-scouts.jpg', class:'img-responsive')